export type Role =
  "superadmin" | "region_admin" | "editor" | "viewer" | "audit_viewer";
export type Permission = "view" | "edit";
export type User = {
  id: string;
  name: string;
  email: string;
  role: Role;
  region: string;
  crossRegionView: boolean;
  permissions: Record<string, Permission[]>;
  passwordHash?: string;
  disabled?: boolean;
  sessionVersion?: number;
};
export type Entity = {
  id: string;
  code: string;
  name: string;
  region: string;
  reportingRegion: string;
  businessUnit: string;
  description: string;
  aliases: string[];
};
export type Amount = number | null;
export type SalesType = "all" | "external" | "group";
export type Scenario = "Sales" | "Sales + Prospect";
export type Split = { external: Amount; group: Amount };
export type OrderBookLine = {
  id: string;
  entityId: string;
  week: number;
  year: number;
  product: string;
  customer: string;
  customerType: "External" | "Group" | "Unclassified";
  dgc: string;
  quantity: Amount;
  total2026: number;
  total2027: number;
  monthly2026: Amount[];
  monthly2027: Amount[];
  sourceFile: string;
  sourceSheet: string;
  sourceRow: number;
};
export type Snapshot = {
  entityId: string;
  year: number;
  week: number;
  month: number;
  asOfDate: string;
  turnover: Split;
  monthTurnover: Split;
  monthEstimate: Split;
  orderbook: Split;
  nextOrderbook: Split;
  baseOverride: Amount;
  monthlyBaseOverride: Amount[] | null;
  prospect: Amount;
  nextProspect: Amount;
  annualBudget: Amount;
  nextAnnualBudget: Amount;
  monthlyBudget: Amount[];
  monthlyProspect: Amount[];
  monthlySales: { external: Amount[]; group: Amount[] };
  monthlyOrderbook: { external: Amount[]; group: Amount[] };
  nextMonthlyOrderbook: { external: Amount[]; group: Amount[] };
  sourceFile: string;
  sourceSheet: string;
  sourceNote: string;
  sourceCells: Record<string, string>;
  findings: string[];
  sourceCheck: "Ready" | "Review";
  publishedAt?: string;
};
export type Finding = { severity: "error" | "review"; message: string };
export type ImportBatch = {
  id: string;
  fileName: string;
  sourceType: "Excel" | "Manual";
  status: "review" | "published" | "rejected";
  entityIds: string[];
  submittedBy: string;
  submittedAt: string;
  publishedBy?: string;
  publishedAt?: string;
  findings: Finding[];
  snapshots: Snapshot[];
  lines: OrderBookLine[];
  sheets: { name: string; rows: number; kind: string }[];
  revision?: number;
};
export type AuditEvent = {
  id: string;
  at: string;
  actor: string;
  action: string;
  subject: string;
};
export type Store = {
  version: number;
  revision: number;
  users: User[];
  snapshots: Snapshot[];
  lines: OrderBookLine[];
  batches: ImportBatch[];
  audit: AuditEvent[];
};
export type Filters = {
  region: string;
  bu: string;
  entity: string;
  year: number;
  scenario: Scenario;
  salesType: SalesType;
};
